# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH key
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_KEY }}

#       - name: Test SSH connection
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

#       - name: Copy project to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/fastapi_supabase"
#           scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/fastapi_supabase

#       - name: Check Docker version
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'docker --version'

#       - name: Deploy on EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
#           cd ~/fastapi_supabase

#           # Create .env from GitHub secret
#           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
#           echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#           echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
#           echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
#           echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
#           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
#           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
#           echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env

#           # Build and run the Docker container
#           sudo docker build -t fastapi-supabase .
#           sudo docker stop fastapi-supabase || true
#           sudo docker rm fastapi-supabase || true
#           sudo docker run -d --name fastapi-supabase --env-file .env -p 8000:8000 fastapi-supabase
#           EOF
