name: Deploy FastAPI App to EC2 (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Copy app directory to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./app ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/fastapi_app

      - name: Install dependencies and run app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/fastapi_app
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pkill uvicorn || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF
