name: Prepare Task Folder

on:
  push:
    branches:
      - main  # run when code is pushed to main branch
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create Task folder structure
      - name: Create Task folder structure
        run: |
          mkdir -p Task/app
          mkdir -p Task/terraform

      # Step 3: Copy FastAPI app files
      - name: Copy FastAPI app files
        run: cp -r app/* Task/app/

      # Step 4: Copy Terraform files
      - name: Copy Terraform files
        run: cp -r Terraform/* Task/terraform/

   
      
