name: Deploy FastAPI App with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Task structure
        run: |
          mkdir -p Task/app
          mkdir -p Task/Terraform

      - name: Copy FastAPI app to Task/app
        run: |
          cp main.py Task/app/
          cp database.py Task/app/
          cp Dockerfile Task/app/
          cp requirements.txt Task/app/
          cp .env Task/app/

      - name: Copy Terraform files to Task/Terraform
        run: |
          cp Terraform/* Task/Terraform/

      - name: Verify structure
        run: tree Task

      # You can add Terraform init/plan/apply steps here if needed
      # - name: Terraform Init
      #   run: terraform -chdir=Task/Terraform init
